apiVersion: apps/v1
kind: Deployment
metadata:
  name: rock-paper-scissors-deployment # Name of the deployment
spec:
  replicas: 2 # Number of replicas (pods) you want to run
  selector:
    matchLabels:
      app: rock-paper-scissors # A label to identify the Pods
  template:
    metadata:
      labels:
        app: rock-paper-scissors # Label for the pod
    spec:
      containers:
        - name: rock-paper-scissors # Name of the container
          image: nvmseff/rock-paper-scissors:latest # name of the image
          imagePullPolicy: Always
          ports:
            - containerPort: 3000 # Port your app is listening on inside the container
