apiVersion: v1
kind: Service
metadata:
  name: rock-paper-scissors-service # Name of the service
spec:
  selector:
    app: rock-paper-scissors # The label to select the Pods for this service
  ports:
    - protocol: TCP
      port: 80 # The external port (accessible to the outside world)
      targetPort: 3000 # The internal port where the app is running inside the container
      nodePort: 30080 # The external port on your node (change this to an available port)
  type: NodePort # Changed this to NodePort for local access
