apiVersion: v1
kind: Service
metadata:
  name: rock-paper-scissors-service # Name of the service
spec:
  selector:
    app: rock-paper-scissors # The label to select the Pods for this service
  ports:
    - protocol: TCP
      port: 80 # The external port (accessible to outside world)
      targetPort: 3000 # The internal port where the app is running inside the container
  type: LoadBalancer # You can change this to NodePort if LoadBalancer is not supported
